<script setup lang="ts">
import { marked } from 'marked'
import {
  type AIChatMessage,
  AIChatProtocolClient,
} from "@microsoft/ai-chat-protocol";




const client = new AIChatProtocolClient('/api/chat/')

// initialize variables and parameters
const isLoading = ref<boolean>(false)
const question = ref<string>("")
const messages = ref<AIChatMessage[]>([]);

// open link in new window


// on new message
const handleSubmit = async () => {
  try {
    // loading true
    isLoading.value = true
    // update messages array
    messages.value.push({ content: question.value, role: "user" })

    // get content of current messages    

    // push empty assistant message
    messages.value.push({ content: "", role: "assistant" })
    // scroll to bottom

    // get response    
    const result = await client.getStreamedCompletion(messages.value);

    for await (const response of result) {
      if (response.sessionState) {
        //do something with the session state returned
      }

      if (response.delta.content) {
        // do something with the content of the message
        messages.value[messages.value.length - 1].content += response.delta.content

      }
    }
    isLoading.value = false
    question.value = ""

  } catch (err: any) {
    console.log(err)
    isLoading.value = false
    messages.value[messages.value.length - 1].content = err.message
    question.value = ""

  }

}

const markdown = ((plainText: string, messageIndex: number) => {  //return marked.parse(plainText);

  return marked.parse(plainText);
})

//handle autoscroll bottom
const chatContainer = ref<HTMLElement | null>(null)






</script>
<template>
  <div class="flex flex-col h-screen p-4 bg-gradient-to-r from-primary-500 to-secondary-500"
    @keyup.enter="handleSubmit">

    <div class="p-4 flex flex-col h-full bg-slate-100/80 dark:bg-slate-800/80 rounded-xl relative">

      <div class="flex-1 overflow-auto gap-2 flex flex-col p-2" ref="chatContainer"
        :class="{ 'items-center justify-center': messages.length === 0 }">

        <div class="flex gap-2 items-center" v-for="(message, index) in messages" :key="index">
          <UIcon
            :name="message.role === 'user' ? 'i-fluent-person-lightbulb-20-filled' : 'i-fluent-bot-sparkle-20-filled'"
            class="size-8 min-w-8 " />
          <div class="flex flex-col ">
            <div v-if="message.content.length === 0 && message.role === 'assistant'"
              class="bg-primary-300 dark:bg-primary-600 rounded-lg p-3 flex flex-col">
              <UIcon name="i-fluent-spinner-ios-20-filled" class="animate-spin gap-1 size-6"></Uicon>
              <div class="italic text-sm">Content generated by AI may include false informations</div>
            </div>
            <div v-else v-html="message.role === 'user' ? message.content : markdown(message.content, index)"
              :class="{ 'bg-primary-300 rounded-t-lg dark:bg-primary-600': message.role === 'assistant', 'bg-secondary-400 dark:bg-secondary-600 rounded-lg': message.role === 'user' }"
              class="p-3">
            </div>


          </div>
        </div>

      </div>

      <form @submit.prevent="handleSubmit"
        class="md:mx-6 relative overflow-hidden rounded-lg border bg-white focus-within:ring-1 focus-within:ring-ring">
        <UTextarea id="message" placeholder="Ask me" :disabled="isLoading" color="primary" variant="none"
          class="min-h-12 resize-none border-0 shadow-none focus-visible:ring-0 text-black p-1" v-model="question" />
        <div class="flex items-center p-3 pt-0 ">


          <UButton type="submit" class="ml-auto gap-1.5" :disabled="isLoading">
            <UIcon name="i-fluent-send-20-regular" class="size-6" />
          </UButton>



        </div>
      </form>
    </div>
  </div>
</template>
